services:
  prefect-server:
    image: prefect:0.9.6
    container_name: prefect-server
    networks:
      - prefect-server-net
    env_file:
      - .env
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: "postgresql+asyncpg://postgres:${PREFECT_POSTGRES_PASSWORD}@prefect-postgres:5432/prefect"
      PREFECT_SERVER_ALLOW_EPHEMERAL_MODE: 'false'
      PREFECT_API_URL: "http://aime.transp.biz:4200/api"
      PREFECT_SERVER_API_AUTH_STRING: ${PREFECT_SERVER_API_AUTH_STRING}
      PREFECT_API_AUTH_STRING: ${PREFECT_API_AUTH_STRING}
    depends_on:
      prefect-postgres:
        condition: service_healthy
    expose:
      - 4200
    ports:
      - "4200:4200"  # Interface do Prefect Server

  prefect-postgres:
    image: postgres:latest
    container_name: prefect-db
    networks:
      - prefect-server-net
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PREFECT_POSTGRES_PASSWORD}
      POSTGRES_DB: prefect
    ports:
      - "5432:5432"
    volumes:
      - prefectdb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d prefect"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  prefectdb:
    driver: local

networks:
  prefect-server-net:
    external: true


